a.out: sync.o save.o admin_fun.o my_AtoF.o in_out_time.o project_main.o
	cc sync.o save.o admin_fun.o my_AtoF.o in_out_time.o project_main.o

sync.o: sync.c
	cc -c sync.c

save.o: save.c
	cc -c save.c

admin_fun.o: admin_fun.c
	cc -c admin_fun.c

my_AtoF.o: my_AtoF.c
	cc -c my_AtoF.c

in_out_time.o: in_out_time.c
	cc -c in_out_time.c

project_main.o: project_main.c
	cc -c project_main.c

/*clean:
	rm -f *.o a.out*/

